# Generated by Django 3.0 on 2019-12-30 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_project_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['date'], 'verbose_name': 'Projet'},
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Image du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(null=True, verbose_name='Description du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du projet'),
        ),
    ]
