# Generated by Django 3.0 on 2019-12-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.CharField(max_length=500, null=True, verbose_name='Image du projet'),
        ),
    ]
