# Generated by Django 3.0 on 2019-12-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date'], 'verbose_name': 'Projet'},
        ),
        migrations.AddField(
            model_name='project',
            name='labels',
            field=models.CharField(max_length=100, null=True, verbose_name='Langages utilisées'),
        ),
    ]
