# Generated by Django 3.0 on 2019-12-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20191230_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lien Démonstration'),
        ),
    ]
