# Generated by Django 3.0 on 2020-01-03 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_router'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='imgproject')),
            ],
            options={
                'verbose_name': 'Fichier',
            },
        ),
        migrations.DeleteModel(
            name='Router',
        ),
    ]
