# Generated by Django 3.0 on 2020-01-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200103_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='specifications',
            field=models.ImageField(upload_to='imgproject', verbose_name='Image'),
        ),
    ]
