# Generated by Django 3.0 on 2020-01-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_auto_20200103_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name="Nom de l'image"),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='specifications',
            field=models.ImageField(null=True, upload_to='imgproject', verbose_name='Image'),
        ),
    ]
