# Generated by Django 3.0 on 2020-01-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_auto_20200103_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='specifications',
            field=models.ImageField(null=True, upload_to='static/img', verbose_name='Image'),
        ),
    ]
