# Generated by Django 3.0 on 2020-01-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_auto_20200103_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(null=True, upload_to='gallery', verbose_name='Image du projet'),
        ),
    ]
