# Generated by Django 3.0 on 2020-01-03 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_auto_20200103_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name="Nom de l'image")),
                ('link', models.ImageField(null=True, upload_to='gallery', verbose_name='Image')),
                ('projet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='portfolio.Project')),
            ],
            options={
                'verbose_name': 'Fichier',
            },
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
