# Generated by Django 3.0 on 2020-02-14 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_auto_20200103_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadimg',
            options={'ordering': ['-name'], 'verbose_name': 'Image'},
        ),
        migrations.AlterField(
            model_name='uploadimg',
            name='projet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
        ),
    ]
